name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
        continue-on-error: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: survey.pdf
          path: main.pdf
          overwrite: true
        continue-on-error: true
      - name: Copy to www
        run: |
          mkdir -p www
          cp main.pdf www/survey.pdf
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
          publish_branch: gh-pages
        continue-on-error: true
